
onnxPath: onnxModelPath


logging:
  level: 5          # FATAL:0  ERROR:1   WARN:2  INFO:3  VERB:4  DEBUG:5 

model_params:
  image:
    - 640
    - 640
    - 3
  num_cls: 1000
  task: 1            # CLASSIFICATION:0  DETECTION:1  SEGMENTATION:2  MULTITASK:3
  device: 1          # CPU:0  GPU:1
  precision: 1       # FP32:0 FP16:1  INT8:2
  # calibration_list: ./calibration/calibration_list_traffic.txt
  # calibration_table: ./calibration/calibration_table_traffic.txt
  # calibration_list: ./calibration/calibration_list_imagenet.txt
  # calibration_table: ./calibration/calibration_table_imagenet.txt
  # calibration_batchsize: 64


